name: terraform-apply

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: "Terraform workspace (e.g., dev, prod)"
        required: true
        default: "dev"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  apply:
    name: Terraform apply (manual)
    runs-on: ubuntu-latest
    environment: prod   # gate with environment protection if you like
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Terraform init
        run: terraform init

      - name: Select/Create workspace
        run: |
          terraform workspace select "${{ github.event.inputs.workspace }}" \
            || terraform workspace new "${{ github.event.inputs.workspace }}"

      - name: Terraform plan (show)
        run: terraform plan -no-color

      - name: Terraform apply
        run: terraform apply -auto-approve

